(cl:defpackage ur10_picking-srv
  (:use )
  (:export
   "VACUUM_CALIBRATION"
   "<VACUUM_CALIBRATION-REQUEST>"
   "VACUUM_CALIBRATION-REQUEST"
   "<VACUUM_CALIBRATION-RESPONSE>"
   "VACUUM_CALIBRATION-RESPONSE"
   "VACUUM_SWITCH"
   "<VACUUM_SWITCH-REQUEST>"
   "VACUUM_SWITCH-REQUEST"
   "<VACUUM_SWITCH-RESPONSE>"
   "VACUUM_SWITCH-RESPONSE"
  ))

