// Generated by gencpp from file ur10_picking/vacuum_switch.msg
// DO NOT EDIT!


#ifndef UR10_PICKING_MESSAGE_VACUUM_SWITCH_H
#define UR10_PICKING_MESSAGE_VACUUM_SWITCH_H

#include <ros/service_traits.h>


#include <ur10_picking/vacuum_switchRequest.h>
#include <ur10_picking/vacuum_switchResponse.h>


namespace ur10_picking
{

struct vacuum_switch
{

typedef vacuum_switchRequest Request;
typedef vacuum_switchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vacuum_switch
} // namespace ur10_picking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_picking::vacuum_switch > {
  static const char* value()
  {
    return "2d82a0d3cd91c1b1995bd03ea0dc40fd";
  }

  static const char* value(const ::ur10_picking::vacuum_switch&) { return value(); }
};

template<>
struct DataType< ::ur10_picking::vacuum_switch > {
  static const char* value()
  {
    return "ur10_picking/vacuum_switch";
  }

  static const char* value(const ::ur10_picking::vacuum_switch&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_picking::vacuum_switchRequest> should match
// service_traits::MD5Sum< ::ur10_picking::vacuum_switch >
template<>
struct MD5Sum< ::ur10_picking::vacuum_switchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_picking::vacuum_switch >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_switchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_picking::vacuum_switchRequest> should match
// service_traits::DataType< ::ur10_picking::vacuum_switch >
template<>
struct DataType< ::ur10_picking::vacuum_switchRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_picking::vacuum_switch >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_switchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_picking::vacuum_switchResponse> should match
// service_traits::MD5Sum< ::ur10_picking::vacuum_switch >
template<>
struct MD5Sum< ::ur10_picking::vacuum_switchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_picking::vacuum_switch >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_switchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_picking::vacuum_switchResponse> should match
// service_traits::DataType< ::ur10_picking::vacuum_switch >
template<>
struct DataType< ::ur10_picking::vacuum_switchResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_picking::vacuum_switch >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_switchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_PICKING_MESSAGE_VACUUM_SWITCH_H
