// Generated by gencpp from file ur10_picking/vacuum_calibration.msg
// DO NOT EDIT!


#ifndef UR10_PICKING_MESSAGE_VACUUM_CALIBRATION_H
#define UR10_PICKING_MESSAGE_VACUUM_CALIBRATION_H

#include <ros/service_traits.h>


#include <ur10_picking/vacuum_calibrationRequest.h>
#include <ur10_picking/vacuum_calibrationResponse.h>


namespace ur10_picking
{

struct vacuum_calibration
{

typedef vacuum_calibrationRequest Request;
typedef vacuum_calibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vacuum_calibration
} // namespace ur10_picking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_picking::vacuum_calibration > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::ur10_picking::vacuum_calibration&) { return value(); }
};

template<>
struct DataType< ::ur10_picking::vacuum_calibration > {
  static const char* value()
  {
    return "ur10_picking/vacuum_calibration";
  }

  static const char* value(const ::ur10_picking::vacuum_calibration&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_picking::vacuum_calibrationRequest> should match
// service_traits::MD5Sum< ::ur10_picking::vacuum_calibration >
template<>
struct MD5Sum< ::ur10_picking::vacuum_calibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_picking::vacuum_calibration >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_calibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_picking::vacuum_calibrationRequest> should match
// service_traits::DataType< ::ur10_picking::vacuum_calibration >
template<>
struct DataType< ::ur10_picking::vacuum_calibrationRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_picking::vacuum_calibration >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_calibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_picking::vacuum_calibrationResponse> should match
// service_traits::MD5Sum< ::ur10_picking::vacuum_calibration >
template<>
struct MD5Sum< ::ur10_picking::vacuum_calibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_picking::vacuum_calibration >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_calibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_picking::vacuum_calibrationResponse> should match
// service_traits::DataType< ::ur10_picking::vacuum_calibration >
template<>
struct DataType< ::ur10_picking::vacuum_calibrationResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_picking::vacuum_calibration >::value();
  }
  static const char* value(const ::ur10_picking::vacuum_calibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_PICKING_MESSAGE_VACUUM_CALIBRATION_H
