// Generated by gencpp from file ur10_picking/vacuum_switchRequest.msg
// DO NOT EDIT!


#ifndef UR10_PICKING_MESSAGE_VACUUM_SWITCHREQUEST_H
#define UR10_PICKING_MESSAGE_VACUUM_SWITCHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_picking
{
template <class ContainerAllocator>
struct vacuum_switchRequest_
{
  typedef vacuum_switchRequest_<ContainerAllocator> Type;

  vacuum_switchRequest_()
    : input(false)  {
    }
  vacuum_switchRequest_(const ContainerAllocator& _alloc)
    : input(false)  {
  (void)_alloc;
    }



   typedef uint8_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct vacuum_switchRequest_

typedef ::ur10_picking::vacuum_switchRequest_<std::allocator<void> > vacuum_switchRequest;

typedef boost::shared_ptr< ::ur10_picking::vacuum_switchRequest > vacuum_switchRequestPtr;
typedef boost::shared_ptr< ::ur10_picking::vacuum_switchRequest const> vacuum_switchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator1> & lhs, const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator1> & lhs, const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_picking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b64ae4a7ed5de74b5f183194512b62f";
  }

  static const char* value(const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b64ae4a7ed5de74ULL;
  static const uint64_t static_value2 = 0xb5f183194512b62fULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_picking/vacuum_switchRequest";
  }

  static const char* value(const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool input\n"
;
  }

  static const char* value(const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vacuum_switchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_picking::vacuum_switchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_picking::vacuum_switchRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_PICKING_MESSAGE_VACUUM_SWITCHREQUEST_H
