// Generated by gencpp from file ur10_picking/vacuum_switchResponse.msg
// DO NOT EDIT!


#ifndef UR10_PICKING_MESSAGE_VACUUM_SWITCHRESPONSE_H
#define UR10_PICKING_MESSAGE_VACUUM_SWITCHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_picking
{
template <class ContainerAllocator>
struct vacuum_switchResponse_
{
  typedef vacuum_switchResponse_<ContainerAllocator> Type;

  vacuum_switchResponse_()
    : output()  {
    }
  vacuum_switchResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct vacuum_switchResponse_

typedef ::ur10_picking::vacuum_switchResponse_<std::allocator<void> > vacuum_switchResponse;

typedef boost::shared_ptr< ::ur10_picking::vacuum_switchResponse > vacuum_switchResponsePtr;
typedef boost::shared_ptr< ::ur10_picking::vacuum_switchResponse const> vacuum_switchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator1> & lhs, const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator1> & lhs, const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_picking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_picking/vacuum_switchResponse";
  }

  static const char* value(const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n"
"\n"
;
  }

  static const char* value(const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vacuum_switchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_picking::vacuum_switchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_picking::vacuum_switchResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_PICKING_MESSAGE_VACUUM_SWITCHRESPONSE_H
