// Generated by gencpp from file ur10_picking/vacuum_calibrationRequest.msg
// DO NOT EDIT!


#ifndef UR10_PICKING_MESSAGE_VACUUM_CALIBRATIONREQUEST_H
#define UR10_PICKING_MESSAGE_VACUUM_CALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_picking
{
template <class ContainerAllocator>
struct vacuum_calibrationRequest_
{
  typedef vacuum_calibrationRequest_<ContainerAllocator> Type;

  vacuum_calibrationRequest_()
    : input()  {
    }
  vacuum_calibrationRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct vacuum_calibrationRequest_

typedef ::ur10_picking::vacuum_calibrationRequest_<std::allocator<void> > vacuum_calibrationRequest;

typedef boost::shared_ptr< ::ur10_picking::vacuum_calibrationRequest > vacuum_calibrationRequestPtr;
typedef boost::shared_ptr< ::ur10_picking::vacuum_calibrationRequest const> vacuum_calibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator1> & lhs, const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator1> & lhs, const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_picking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_picking/vacuum_calibrationRequest";
  }

  static const char* value(const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n"
;
  }

  static const char* value(const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vacuum_calibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_picking::vacuum_calibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_PICKING_MESSAGE_VACUUM_CALIBRATIONREQUEST_H
