#!/bin/bash

cd catkin_ws/src
git clone -b melodic-devel https://github.com/ros-industrial/universal_robot.git
cd ..
catkin_make
echo "source ~/farscope_group_project/catkin_ws/devel/setup.bash" >> ~/.bashrc
source ~/.bashrc
sudo apt-get install ros-melodic-ros-control ros-melodic-ros-controllers
